travis:
  secure:
    BINSTAR_TOKEN: rLtnfE8hzrR56TzxbGMvNq1LIyKF3UXvF7ryaBMHLuO9nLvNpYgz5hKJRg8YHvFyykX/oMXIGMi0qVYviUFWuaLz5QbPkTs0YxBCO1QZ43xpEJwoMsmfa0md70G5xHI2V4I3wRSYqL5BLSUKvY3sdZaF5gbluSwFZrrs7KRQev3qA5ztv9TsYl+WJCuh0EbZp9Vqsrwx94fLgoehVTT6RCizONSaq2R+36RI5VLOPBkSrWSPu0+WZ3za3VklFBCLK2Fb2oomcXavyMVo1SRoFINwwsenC3FYevi7VmcIIqsrrISRk2dyIY0VLP4bsqdOxzKVkHPfOWm12dNXREsSewuOgzbzqFTRMMHwwlIx85rPcaOy7t2OYaDB6LxMsebSJuOTr/u4EF/0oZCqkgPrrFDn8MPOKppMpDkMPjzU/1ofNXmNPoj7z7uaUyPCIxfYveJZGt0uNb10+5EMNIsWfCfYVMb89jwiFpUDk2SsQsolxDJRoRs8y/ApE9+dXFkYJb/ndu164o/Ak+Ci8dqQXYwA5hJnO6AAs+BLuW6Ik36oSDuIL9o6oWzEcrZ2PBHDjYnJzm4js8pnKz6oY8Df6wnfcYQGceMWXFafyw8hw1vRASqq0XE0E302pj63GSRIS0xBquQ8AFcQsWV0qr9MmjEIGmquWQBN1l4zwxBSTU4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
